[package]
name = "bomb_shell"
version = "0.1.0"
authors = ["Robley Gori <robleygori@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
